services:
  # Backend API service
  - type: web
    name: quicknotes-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend static site
  - type: web
    name: quicknotes-frontend
    env: static
    buildCommand: echo "No build step needed for static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index-with-backend.html
    envVars:
      - key: API_URL
        fromService:
          name: quicknotes-api
          type: web
          property: url
    autoDeploy: true
